export const API_ERROR_CODES = {
  INVALID_KEY: 'INVALID_KEY',
  KEY_REVOKED: 'KEY_REVOKED',
  API_NOT_ENABLED: 'API_NOT_ENABLED',
  RATE_LIMIT_RPM: 'RATE_LIMIT_RPM',
  RATE_LIMIT_RPD: 'RATE_LIMIT_RPD',
  RATE_LIMIT_TPM: 'RATE_LIMIT_TPM',
  SERVER_ERROR: 'SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  SERVER_OVERLOADED: 'SERVER_OVERLOADED',
  NETWORK_OFFLINE: 'NETWORK_OFFLINE',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  CONTENT_BLOCKED: 'CONTENT_BLOCKED',
  CONTEXT_TOO_LONG: 'CONTEXT_TOO_LONG',
  EMPTY_RESPONSE: 'EMPTY_RESPONSE',
  UNKNOWN: 'UNKNOWN',
};

export const API_ERROR_MESSAGES = {
  [API_ERROR_CODES.INVALID_KEY]: {
    title: 'API Key không hợp lệ',
    description: 'Key bạn nhập bị sai hoặc đã bị xóa.',
    steps: ['Kiểm tra lại key — đảm bảo copy đầy đủ', 'Vào AI Studio để lấy key mới nếu cần'],
    actions: [
      { label: 'Cập nhật API Key', type: 'open-settings' },
      { label: 'Lấy key mới →', type: 'open-url', url: 'https://aistudio.google.com/apikey' },
    ],
    severity: 'error', retryable: false,
  },
  [API_ERROR_CODES.KEY_REVOKED]: {
    title: 'API Key đã bị vô hiệu hóa',
    description: 'Key này không còn hoạt động. Có thể bạn đã xóa nó.',
    steps: ['Vào AI Studio và tạo key mới', 'Dán key mới vào phần cài đặt'],
    actions: [
      { label: 'Cập nhật API Key', type: 'open-settings' },
      { label: 'Tạo key mới →', type: 'open-url', url: 'https://aistudio.google.com/apikey' },
    ],
    severity: 'error', retryable: false,
  },
  [API_ERROR_CODES.API_NOT_ENABLED]: {
    title: 'Generative Language API chưa được bật',
    description: 'Project Google Cloud chưa kích hoạt Gemini API.',
    steps: ['Vào Google Cloud Console', 'Tìm "Generative Language API"', 'Click Enable'],
    actions: [
      { label: 'Bật API ngay →', type: 'open-url', url: 'https://console.cloud.google.com/apis/library/generativelanguage.googleapis.com' },
    ],
    severity: 'error', retryable: false,
  },
  [API_ERROR_CODES.RATE_LIMIT_RPM]: {
    title: 'Gửi quá nhiều yêu cầu cùng lúc',
    description: 'API giới hạn số request mỗi phút. App đang tự động chờ và thử lại.',
    steps: ['Không cần làm gì — app sẽ tự retry sau vài giây'],
    actions: [{ label: 'Thử lại', type: 'retry' }],
    severity: 'warning', retryable: true, retryAfterMs: 65000,
  },
  [API_ERROR_CODES.RATE_LIMIT_RPD]: {
    title: 'Đã dùng hết quota hôm nay',
    description: 'Free tier giới hạn ~250 request/ngày. Quota reset lúc 14:00 (giờ VN).',
    steps: ['Chờ đến 14:00 để quota reset', 'Hoặc nâng cấp Paid key để dịch không giới hạn'],
    actions: [
      { label: 'Xuất phần đã dịch', type: 'export' },
      { label: 'Nâng cấp Paid Key →', type: 'upgrade' },
    ],
    severity: 'error', retryable: false,
  },
  [API_ERROR_CODES.RATE_LIMIT_TPM]: {
    title: 'Đoạn văn quá dài cho một lần gửi',
    description: 'Vượt giới hạn token/phút. App sẽ tự thử lại.',
    steps: ['App sẽ tự chia nhỏ và thử lại'],
    actions: [{ label: 'Thử lại', type: 'retry' }],
    severity: 'warning', retryable: true, retryAfterMs: 65000,
  },
  [API_ERROR_CODES.SERVER_ERROR]: {
    title: 'Lỗi máy chủ AI',
    description: 'Server AI đang gặp sự cố. Không phải lỗi từ phía bạn.',
    steps: ['Thử lại sau 1–2 phút', 'Kiểm tra status.cloud.google.com'],
    actions: [
      { label: 'Thử lại', type: 'retry' },
      { label: 'Xem trạng thái →', type: 'open-url', url: 'https://status.cloud.google.com' },
    ],
    severity: 'error', retryable: true, retryAfterMs: 30000,
  },
  [API_ERROR_CODES.SERVICE_UNAVAILABLE]: {
    title: 'Dịch vụ AI tạm thời không khả dụng',
    description: 'Server đang bảo trì hoặc quá tải. Thường phục hồi trong vài phút.',
    steps: ['Chờ 2–5 phút rồi thử lại', 'Thử đổi sang provider khác'],
    actions: [{ label: 'Thử lại', type: 'retry' }],
    severity: 'error', retryable: true, retryAfterMs: 120000,
  },
  [API_ERROR_CODES.SERVER_OVERLOADED]: {
    title: 'Server AI đang quá tải',
    description: 'Quá nhiều người dùng cùng lúc. Thường tự hết sau vài phút.',
    steps: ['Chờ 3–5 phút rồi thử lại'],
    actions: [{ label: 'Thử lại', type: 'retry' }],
    severity: 'warning', retryable: true, retryAfterMs: 180000,
  },
  [API_ERROR_CODES.NETWORK_OFFLINE]: {
    title: 'Mất kết nối internet',
    description: 'Không thể kết nối tới server. Kiểm tra mạng của bạn.',
    steps: ['Kiểm tra Wi-Fi hoặc mạng', 'Thử mở trang web khác để xác nhận'],
    actions: [{ label: 'Thử lại', type: 'retry' }],
    severity: 'error', retryable: true, retryAfterMs: 5000,
  },
  [API_ERROR_CODES.NETWORK_TIMEOUT]: {
    title: 'Yêu cầu bị timeout',
    description: 'Server mất quá lâu để phản hồi. Đoạn văn có thể quá dài.',
    steps: ['Thử lại — thường chỉ là tạm thời'],
    actions: [{ label: 'Thử lại', type: 'retry' }],
    severity: 'warning', retryable: true, retryAfterMs: 5000,
  },
  [API_ERROR_CODES.CONTENT_BLOCKED]: {
    title: 'Nội dung bị chặn bởi bộ lọc an toàn',
    description: 'AI từ chối xử lý đoạn này vì phát hiện nội dung nhạy cảm.',
    steps: ['Kiểm tra nội dung đoạn văn', 'Thử đổi sang provider khác'],
    actions: [
      { label: 'Bỏ qua đoạn này', type: 'skip' },
      { label: 'Thử lại', type: 'retry' },
    ],
    severity: 'warning', retryable: false,
  },
  [API_ERROR_CODES.CONTEXT_TOO_LONG]: {
    title: 'Đoạn văn vượt quá giới hạn token',
    description: 'Section này quá dài. Hãy chia nhỏ tài liệu.',
    steps: ['Chia tài liệu thành file nhỏ hơn (< 100 trang)'],
    actions: [{ label: 'Bỏ qua đoạn này', type: 'skip' }],
    severity: 'error', retryable: false,
  },
  [API_ERROR_CODES.EMPTY_RESPONSE]: {
    title: 'AI không trả về kết quả',
    description: 'Response rỗng. Hiếm gặp, thường tự hết khi thử lại.',
    steps: ['Thử lại — thường chỉ xảy ra 1 lần'],
    actions: [{ label: 'Thử lại', type: 'retry' }],
    severity: 'warning', retryable: true, retryAfterMs: 3000,
  },
  [API_ERROR_CODES.UNKNOWN]: {
    title: 'Đã xảy ra lỗi không xác định',
    description: 'Lỗi chưa được nhận diện. Vui lòng thử lại hoặc báo cáo.',
    steps: ['Thử lại một lần', 'Nếu vẫn lỗi: gửi báo cáo'],
    actions: [
      { label: 'Thử lại', type: 'retry' },
      { label: 'Báo cáo lỗi', type: 'report' },
    ],
    severity: 'error', retryable: true, retryAfterMs: 5000,
  },
};
